name: Release

on:
  push:
    branches:
      - main
      - master

env:
  NODE_VERSION: '20'

jobs:
  release:
    name: Release (GH)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          registry-url: https://npm.pkg.github.com
          node-version: ${{ env.NODE_VERSION }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release-npm:
    name: Release (NPM)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org
          node-version: ${{ env.NODE_VERSION }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
