name: Test

on: [push]

env:
  NODE_VERSION: '24'

jobs:
  chewtoy:
    name: Chewtoy validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      - name: Validate against Chewtoy
        run: pnpm run validate
